https://www.perplexity.ai/search/0638400d-59de-4d83-8e38-0cb807daf590

In [4]:
import numpy as np
from numpy import ndarray

my_array:ndarray = np.arange(1000000)
my_list = list(range(1000000))

In [5]:
%time 

for _ in range(10):
    #list的comprehension,list綜合表達式
    my_lists = [x*2 for x in my_list]

CPU times: total: 0 ns
Wall time: 0 ns


In [6]:
%time for _ in range(10): my_array2 = my_array * 2

CPU times: total: 46.9 ms
Wall time: 65.6 ms


In [7]:
np.array(range(4)).shape

(4,)

In [ ]:
###50個學生, 每個學生有5個分數, 每個分數50~100


In [ ]:
np.random.seed(42)#42 seed去產生亂數後就不會再動 python內建不能這做, 只有numpy才可以
scores = np.random.randint(50,101,(50,5))
scores

#ndarray常用的實體屬性
#scores.ndim
scores.shape
scores.size
scores.dtype

###基本索引和分割
- ndarray[index]
- ndayyay[start:end:step]

In [32]:
#2維
scores[0][4]#類似list的操作
scores[0, 4]#ndarrya的slice的操作法

np.int32(57)

In [33]:
##取得第1位學生的分數
scores[0]#shape(5,)
scores[0,:]#shape(5,0)
scores[0:1,:]#shape(1,5)

array([[88, 78, 64, 92, 57]], dtype=int32)

In [39]:
##取得第1,2位學生的分數
scores[:2]
scores[:2,:]#和第2列的意思相同
scores[(0,1),:]#和第2列的意思相同
scores[(0,1),:]#和第2列的意思相同
##取得第1,2,5位學生的分數
scores[(0,1,4),:]

array([[88, 78, 64, 92, 57],
       [70, 88, 68, 72, 60],
       [79, 87, 51, 70, 82]], dtype=int32)

In [ ]:
##取得第1科的所有分數
scores[:,0]#(50,)
scores[:,0:1]#(1,50)

In [ ]:
##取得第1,2科的所有分數
scores[:,:2]#(50,2)

In [ ]:
##取得前30位學生的最後3科分數
scores[:30,-3:]#(30,3)

###ndarray的統計的實體方法
- sum()
- min()
- max()
- mean()

In [46]:
#每個學生的總分和平均
scores.sum(axis=1)


array([379, 358, 380, 340, 369, 397, 373, 427, 372, 356, 330, 398, 397,
       339, 366, 370, 353, 385, 412, 376, 311, 383, 373, 400, 315, 410,
       413, 400, 294, 349, 392, 401, 419, 381, 385, 368, 411, 381, 330,
       334, 452, 372, 435, 385, 343, 371, 368, 315, 352, 375])

In [48]:
#前30位學生的平均
scores[:30].mean(axis=1)

array([75.8, 71.6, 76. , 68. , 73.8, 79.4, 74.6, 85.4, 74.4, 71.2, 66. ,
       79.6, 79.4, 67.8, 73.2, 74. , 70.6, 77. , 82.4, 75.2, 62.2, 76.6,
       74.6, 80. , 63. , 82. , 82.6, 80. , 58.8, 69.8])

In [50]:
#第1科最高的分數和最低分
scores[:,0].max(axis=0)
scores[:,0].min(axis=0)

np.int32(50)